# Generated by Django 3.2.9 on 2022-02-07 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import telehealth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('street', models.CharField(max_length=120)),
                ('zip_code', models.CharField(max_length=10, validators=[telehealth.models.isDigitValidator])),
            ],
        ),
        migrations.CreateModel(
            name='Specialities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialitie', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(choices=[('Clinical', 'Clinical'), ('Online', 'Online')], max_length=10)),
                ('consultation_price', models.IntegerField()),
                ('insurance_company', models.CharField(max_length=120)),
                ('insurance_number', models.CharField(max_length=120, validators=[telehealth.models.isDigitValidator])),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telehealth.address')),
                ('specialities', models.ManyToManyField(to='telehealth.Specialities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
